apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  ports:
    - name: "5080"
      port: 5080
      targetPort: 5005
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: api-gateway
