apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  strategy: {}
  template:
    spec:
      containers:
        - env:
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_URI
              value: http://eureka:8761/eureka/
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_ZIPKIN_BASEURL
              value: http://zipkin:9411
          image: gateway
          name: gateway
          imagePullPolicy: Never
          ports:
            - containerPort: 5005
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
    metadata:
      labels:
        app: gateway
status: {}
