apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: po
  name: po
spec:
  ports:
  - name: "5020"
    port: 5020
    targetPort: 5005
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    io.kompose.service: po
status:
  loadBalancer: {}
