server:
  port: 8082

#mongo configuration
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
---

#eureka configuration
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetchRegistry: true
    registerWithEureka: true

spring:
  cloud:
    config:
      enabled: false
  application:
    name: po
  sleuth:
    sampler:
      probability: 0.9
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASEURL:http://localhost:9411}

#feign configuration
feign:
  client:
    config:
      po:
        connectTimeout: 800
        readTimeout: 500
        loggerLevel: full
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 11000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

logging:
  level:
    org:
      springframework:
        cloud: info