#eureka configuration
eureka:
  instance:
    lease-renewal-interval-in-seconds: 1 #for dev purpose only
    lease-expiration-duration-in-seconds: 2 #for dev purpose only
  client:
    initial-instance-info-replication-interval-seconds: 0 #for dev purpose only
    instance-info-replication-interval-seconds: 1 #for dev purpose only
    registryFetchIntervalSeconds: 1 #for dev purpose only

spring:
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    org:
      springframework:
        cloud: debug