package org.nipu.po.order;

import lombok.extern.slf4j.Slf4j;
import org.nipu.po.order.clients.ProductSpecificationRepository;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * TODO: This is autogenerated Java-Doc.
 *
 * @author Nikita_Puzankov
 */
@RestController
@Slf4j
public class OrderController {
    private static final long DEFAULT_QUANTITY = 1L;

    private final ProductOrderRepository orderRepository;
    private final ProductSpecificationRepository specificationRepository;

    public OrderController(ProductOrderRepository orderRepository, ProductSpecificationRepository specificationRepository) {
        this.orderRepository = orderRepository;
        this.specificationRepository = specificationRepository;
    }

    @PutMapping("/catalog/{specificationId}/order")
    public ResponseEntity<ProductOrder> orderProductBySpecificationId(@PathVariable String specificationId) {
        if (specificationRepository.existsById(specificationId) == null) {
            log.warn("There is no product specification with Id: {}", specificationId);
            return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
        }
        ProductOrder order = orderRepository.save(new ProductOrder(null, specificationId, DEFAULT_QUANTITY));
        return ResponseEntity.status(HttpStatus.OK).
                body(order);
    }
}
